# DESCRIBES THE PARAMETERS FOR THE SIMULATION
import numpy as np
import pdb

'''Environment'''

HUB_LOCATION = (0, 0)

SITE_SIZE = 20

ENVIRONMENT_BOUNDARY_X = (-1000, -1000, 1000, 1000)
ENVIRONMENT_BOUNDARY_Y = (-1000, 1000, 1000, -1000)

TIME_LIMIT = 35000

'''Agent'''

AGENT_SPEED = 5.0
AGENT_AGENT_SENSING_DISTANCE = 20.0
EXPLORE_RANDOMNESS = 0.1
EXPLORE_DIRECTION_CHANGE = np.pi/30

BINOMIAL_COEFF_REST_TO_ASSESS = 0.1 # Rest to Travel_Site for Assess
BINOMIAL_COEFF_ASSESS_TO_DANCE = 0.1 # Assess to Travel_Hub for Dance
BINOMIAL_COEFF_EXPLORE_TO_REST = 0.01 # Explore to Travel_Hub for Rest
BINOMIAL_COEFF_DANCE_TO_REST = 0.05 # Dance to Rest
BINOMIAL_COEFF_REST_TO_EXPLORE = 0.05 # Rest to Explore

# for the detachment
base_DANCE_TO_ASSESS = 10.0
pwr_DANCE_TO_ASSESS = -1.0
